//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.18408
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MFramework.Domain.DataAnnotationsContrib {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MFramework.Domain.DataAnnotationsContrib.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The array passed was empty. Expected a length &gt; 0..
        /// </summary>
        internal static string ArgumentException_EmptyArray {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value specified cannot be an empty string..
        /// </summary>
        internal static string ArgumentException_EmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The array passed was of an unexpected length. Expected a length of &apos;{0}&apos;..
        /// </summary>
        internal static string ArgumentException_InvalidArrayLength {
            get {
                return ResourceManager.GetString("ArgumentException_InvalidArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value specified ({1}) was out of the range of acceptable values. Expected a minimum of {0}..
        /// </summary>
        internal static string ArgumentOutOfRangeException_NotGreaterThan {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value specified ({1}) was out of the range of acceptable values. Expected a maximum of {0}..
        /// </summary>
        internal static string ArgumentOutOfRangeException_NotLessThan {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The index specified ({3}) was out of the range of acceptable values. Expected a valid index into list &apos;{0}&apos; between {1} and {2}..
        /// </summary>
        internal static string ArgumentOutOfRangeException_NotValidIndex {
            get {
                return ResourceManager.GetString("ArgumentOutOfRangeException_NotValidIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value specified ({1}) did not match the required format. Expected: &apos;{0}&apos;..
        /// </summary>
        internal static string FormatException_NotRegexMatch {
            get {
                return ResourceManager.GetString("FormatException_NotRegexMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number has an an invalid Basic Bank Account Number format for the specified country..
        /// </summary>
        internal static string Iso13616IBANAlgorithm_InvalidBBANFormat {
            get {
                return ResourceManager.GetString("Iso13616IBANAlgorithm_InvalidBBANFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number has an an invalid Basic Bank Account Number length for the specified country..
        /// </summary>
        internal static string Iso13616IBANAlgorithm_InvalidBBANLength {
            get {
                return ResourceManager.GetString("Iso13616IBANAlgorithm_InvalidBBANLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number is from an invalid (non IBAN) country..
        /// </summary>
        internal static string Iso13616IBANAlgorithm_InvalidCountry {
            get {
                return ResourceManager.GetString("Iso13616IBANAlgorithm_InvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number was valid but from an unaccepted card issuer..
        /// </summary>
        internal static string PaymentCardValidator_CardTypeNotAccepted {
            get {
                return ResourceManager.GetString("PaymentCardValidator_CardTypeNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The number was not of a recognized card issuer format..
        /// </summary>
        internal static string PaymentCardValidator_CardTypeNotRecognized {
            get {
                return ResourceManager.GetString("PaymentCardValidator_CardTypeNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The specified resource &apos;{0}&apos; could not be found in assembly &apos;{1}&apos;..
        /// </summary>
        internal static string ResourceHelper_ArgumentException_ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceHelper_ArgumentException_ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The country specified &apos;{0}&apos; does not have postcode system to validate against..
        /// </summary>
        internal static string UpuPostalCodeAlgorithm_InvalidCountry {
            get {
                return ResourceManager.GetString("UpuPostalCodeAlgorithm_InvalidCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed internal checksum validation..
        /// </summary>
        internal static string Validator_ChecksumFailure {
            get {
                return ResourceManager.GetString("Validator_ChecksumFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The {0} information within the value was not of a valid format..
        /// </summary>
        internal static string Validator_ExtractFailure {
            get {
                return ResourceManager.GetString("Validator_ExtractFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed format validation..
        /// </summary>
        internal static string Validator_FormatFailure {
            get {
                return ResourceManager.GetString("Validator_FormatFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value includes an explicitly prohibited letter/digit sequence..
        /// </summary>
        internal static string Validator_InvalidSequence {
            get {
                return ResourceManager.GetString("Validator_InvalidSequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed length validation..
        /// </summary>
        internal static string Validator_LengthFailure {
            get {
                return ResourceManager.GetString("Validator_LengthFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed length (maximum) validation..
        /// </summary>
        internal static string Validator_LengthMaxFailure {
            get {
                return ResourceManager.GetString("Validator_LengthMaxFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed length (minimum) validation..
        /// </summary>
        internal static string Validator_LengthMinFailure {
            get {
                return ResourceManager.GetString("Validator_LengthMinFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed range (maximum) validation..
        /// </summary>
        internal static string Validator_RangeMaxFailure {
            get {
                return ResourceManager.GetString("Validator_RangeMaxFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed range (minimum) validation..
        /// </summary>
        internal static string Validator_RangeMinFailure {
            get {
                return ResourceManager.GetString("Validator_RangeMinFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value is reserved for advertising purposes..
        /// </summary>
        internal static string Validator_ReservedForAdvertising {
            get {
                return ResourceManager.GetString("Validator_ReservedForAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed size (maximum) validation..
        /// </summary>
        internal static string Validator_SizeMaxFailure {
            get {
                return ResourceManager.GetString("Validator_SizeMaxFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a The value failed size (minimum) validation..
        /// </summary>
        internal static string Validator_SizeMinFailure {
            get {
                return ResourceManager.GetString("Validator_SizeMinFailure", resourceCulture);
            }
        }
    }
}
